### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sibsfinx** [BrandyMint/brandymint2013#2]
- [ ] Convead.com video
### Development
- [ ] deploy via jenkins
### Content
- [ ] add Anna page
- [x] add partners logos (Важных партнеров, наград, проектов в которых принимали участие)
- [x] add team
- [ ] add team photos
- [x] add our services after splash pic
### Design
- [x] test and fix on real devices: iphone, ipad (portrait + landscape)
- [x] fix navbar on ipad portrait
- [ ] add masonry responsive
